website/models.py
class Venue:
    def __init__(self, name, location, frequency, genre, link):
        self._name = name
        self._location = location
        self._frequency = frequency
        self._genre = genre
        self._link = link

    @property
    def name(self):
        return self._name

    @property
    def location(self):
        return self._property

    @property
    def frequency(self):
        return self._frequency

    @property
    def genre(self):
        return self._genre

    @property
    def link(self):
        return self._link

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path


def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "change this for production"  # todo

    from .views.views import views

    app.register_blueprint(views, url_prefix="/")

    return app

website/views/views.py
from flask import Blueprint, render_template
from ..utils import venue_service

views = Blueprint("views", __name__)


@views.route("/")
def home():
    return render_template("home.html")


@views.route("/location/<location>")
def location(location):
    venues = venue_service.get_venues(location)
    location_name = get_proper_location_name(location)
    return render_template("location.html", location_name=location_name, venues=venues)


def get_proper_location_name(location):
    match location:
        case "allbright":
            return "Allston/Brighton"
        case "camberville":
            return "Cambridge/Somerville"
        case "downtown":
            return "Downtown"
        case "elsewhere":
            return "Elsewhere"
        case _:
            raise NotImplementedError

website/templates/base.html
<!DOCTYPE html>
<html data-bs-theme="dark">

<head>
    <meta charset="utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1" />
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous">
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"
        integrity="sha384-4LISF5TTJX/fLmGSxO53rV4miRxdg84mZsxmO8Rx5jGtp/LbrixFETvWa5a6sESd"
        crossorigin="anonymous">
    <link rel="stylesheet"
        href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet"
        href="{{ url_for('static', filename='icons/icons.css') }}">
    {% block stylesheets %}{% endblock %}
    <title>Live Music Boston</title>
</head>

<body>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger alert-dismissible fade show"
        role="alert">
        {{ message }}
        <button type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}


    <a href="{{ url_for('views.home') }}"
        class="btn btn-icon btn-lg">
        <div class="hoverable icon-guitar"></div>
    </a>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

    <script src="{{ url_for('static', filename='changeFillOnHover.js') }}"></script>
    {% block scripts %}{% endblock %}
</body>

</html>

website/templates/home.html
{% extends "base.html" %}

{% block content %}
{% block stylesheets %}
<link rel="stylesheet"
    href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
    integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
    crossorigin="" />
{% endblock %}

{% block scripts %}
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
    integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
    crossorigin=""></script>
{% endblock %}

{% endblock %}

website/templates/location.html
{% extends "base.html" %}

{% block content %}
<h1>Live Music {{ location_name }}</h1>
<br>

{% for venue in venues %}
<p>
    <a href="{{ venue.link }}"
        target="_blank">{{ venue.name }}
    </a>
    - {{ venue.frequency }} - {{ venue.genre }}
</p>
<br>
{% endfor %}

{% endblock %}